#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:#    hibernate:#      ddl-auto: update

spring:
  datasource:
    url: jdbc:h2:mem:testdb
  data:    web:      pageable:
        default-page-size: 10
        max-page-size: 100
                jpa:    properties:      javax:
        persistence:
          validation:
            mode: none
            