#spring:
#  datasource:
#    url: jdbc:h2:./devdb
#    username: sa
#  jpa:#    hibernate:#      ddl-auto: update

spring:
  datasource:
    url: jdbc:h2:mem:testdb
          jpa:    properties:      javax:
        persistence:
          validation:
            mode: none